---
root: true

plugins:
  - babel

env:
  node: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"

rules:
  no-console: 0
  no-case-declarations: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]